version: "3.9"
name: nok-admin-app
services:
    nginx_default:
        restart: always
        container_name: nginx_default
        image: nginx:1.23.3-alpine
        ports:
            - 80:80
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ../:/var/www/
            - ../logs/nginx:/var/log/nginx
        links:
            - php_default
        networks:
            - internal
    php_default:
        restart: always
        container_name: php_default
        build: ./php
        working_dir: /var/www/
        volumes:
            - ../:/var/www/
            - ../logs/php:/var/log
            - ./php/php.ini:/usr/local/etc/php/php.ini-development
            - ./php/php.ini:/usr/local/etc/php/php.ini-production
            - ./php/php.ini:/usr/local/etc/php/php.ini
        networks:
            - internal
        depends_on:
            database:
                condition: service_healthy
        ports:
            - 9000:9000
    database:
        container_name: database
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: superadmin
            MYSQL_USER: fuzi
            MYSQL_PASSWORD: fuzi123
            MYSQL_DATABASE: nok
        ports:
            - 3306:3306
        volumes:
            - ./db/:/var/lib/mysql/
        networks:
            - internal
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 1s
            timeout: 10s
            retries: 5
networks:
    internal:
        driver: bridge
